
# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root
root = "."
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "make build-air"
# Binary file yields from `cmd`.
bin = "tmp/app"

# Customize binary.
# This is how you start to run your application.
# Add any flags if it has any
full_bin = "./tmp/app/engine"
# This log file places in your tmp_dir.
log = "air_errors.log"
# Watch these filename extensions.
include_ext = ["go", "yaml"]
# Ignore these filename extensions or directories.
exclude_dir = ["tmp", "vendor"]
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms

[log]
# Show log time
time = true

[misc]
# Delete tmp directory on exit
clean_on_exit = true
